WITH DATA2 AS
(SELECT SCHEDULE_ATTRIBUTE_DESC1, SCHEDULE_ATTRIBUTE1,
SCHEDULE_ATTRIBUTE_DESC2, SCHEDULE_ATTRIBUTE2,
SCHEDULE_ATTRIBUTE_DESC3, SCHEDULE_ATTRIBUTE3,
SCHEDULE_ATTRIBUTE_DESC4, SCHEDULE_ATTRIBUTE4,
SCHEDULE_ATTRIBUTE_DESC5, SCHEDULE_ATTRIBUTE5,
ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER
FROM Z_NEU_CLASS_DAILY_VW)

SELECT ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER,
SCHEDULE_ATTRIBUTE_DESC1 AS COURSE_ATTRIBUTE FROM DATA2

UNION
SELECT ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER,
SCHEDULE_ATTRIBUTE_DESC2 AS COURSE_ATTRIBUTE2 FROM DATA2
WHERE SCHEDULE_ATTRIBUTE_DESC2 IS NOT NULL

UNION
SELECT ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER,
SCHEDULE_ATTRIBUTE_DESC3 AS COURSE_ATTRIBUTE3 FROM DATA2
WHERE SCHEDULE_ATTRIBUTE_DESC3 IS NOT NULL

UNION
SELECT ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER,
SCHEDULE_ATTRIBUTE_DESC4 AS COURSE_ATTRIBUTE4 FROM DATA2
WHERE SCHEDULE_ATTRIBUTE_DESC4 IS NOT NULL

UNION
SELECT ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER,
SCHEDULE_ATTRIBUTE_DESC5 AS COURSE_ATTRIBUTE5 FROM DATA2
WHERE SCHEDULE_ATTRIBUTE_DESC5 IS NOT NULL
