WITH DATA AS
(SELECT UC_ENROLLMENT, UG_ENROLLMENT, UP_ENROLLMENT, US_ENROLLMENT, CP_ENROLLMENT, MIN_BILLING, MIN_CREDITS, MIN_LAB_HOURS, TOTAL_CREDIT_HOURS, TOTAL_ENROLLMENT, MAX_BILLING, MAX_CREDITS, MAX_LAB_HOURS, MAXIMUM_ENROLLMENT, ACTUAL_ENROLLMENT, GP_ENROLLMENT, GR_ENROLLMENT, END_DATE, SCHEDULE, INSTRUCTOR_JOB_GRADE, INSTRUCTOR_HR_DIV, INSTRUCTOR_HR_DIV_DESC,INSTRUCTOR_HR_DEPT_DESC, INSTRUCTOR_HR_DEPTID, HONORS_TYPE, FACULTY_TENURE, FACULTY_MEMBER_CATEGORY, ACADEMIC_RANK, TITLE_LONG_DESC, TITLE_SHORT_DESC, SUBJECT, SUBJECT_DESC, SCHEDULE_DESC, SECTION_CROSS_LIST,SCHEDULE_ATTRIBUTE_DESC1,SCHEDULE_ATTRIBUTE1,ROOM1, PRIMARY_INSTRUCTOR_LAST_NAME, PRIMARY_INSTRUCTOR_FIRST_NAME, INSTRUCTOR_ROLE, INSTRUCTIONAL_METHOD, INSTRUCTIONAL_METHOD_DESC, DEPARTMENT, DEPARTMENT_DESC, COURSE_NUMBER_COREQ, COURSE_LEVEL_DESC, COURSE_NUMBER, COURSE_IDENTIFICATION, COURSE_LEVEL, COURSE_CLASSIFICATION_GROUPING, CAMPUS, CAMPUS_DESC, COLLEGE, COLLEGE_DESC, BUILDING1, BUILDING_DESC1, ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, 
START_DATE, ACADEMIC_PERIOD_DESC, MEETING_TIME,
SUBSTR(REPLACE(regexp_replace((REGEXP_SUBSTR(MEETING_TIME,'[^ ]+',1,1)) , '(.)', '\1 '), '-', '.'), 1,10) as WEEKDAYS,
trim(regexp_substr(MEETING_TIME, '\ [^,]+\ ' , 1,1)) AS WEEKDAY_B
FROM Z_NEU_CLASS_DAILY_VW)

SELECT UC_ENROLLMENT, UG_ENROLLMENT, UP_ENROLLMENT, US_ENROLLMENT, CP_ENROLLMENT, MIN_BILLING, MIN_CREDITS, MIN_LAB_HOURS, TOTAL_CREDIT_HOURS, TOTAL_ENROLLMENT, MAX_BILLING, MAX_CREDITS, MAX_LAB_HOURS, MAXIMUM_ENROLLMENT, ACTUAL_ENROLLMENT, GP_ENROLLMENT, GR_ENROLLMENT, END_DATE, SCHEDULE, INSTRUCTOR_JOB_GRADE, INSTRUCTOR_HR_DIV, INSTRUCTOR_HR_DIV_DESC,INSTRUCTOR_HR_DEPT_DESC, INSTRUCTOR_HR_DEPTID, HONORS_TYPE, FACULTY_TENURE, FACULTY_MEMBER_CATEGORY, ACADEMIC_RANK, TITLE_LONG_DESC, TITLE_SHORT_DESC, SUBJECT, SUBJECT_DESC, SCHEDULE_DESC, SECTION_CROSS_LIST,SCHEDULE_ATTRIBUTE_DESC1,SCHEDULE_ATTRIBUTE1,ROOM1, PRIMARY_INSTRUCTOR_LAST_NAME, PRIMARY_INSTRUCTOR_FIRST_NAME, INSTRUCTOR_ROLE, INSTRUCTIONAL_METHOD, INSTRUCTIONAL_METHOD_DESC, DEPARTMENT, DEPARTMENT_DESC, COURSE_NUMBER_COREQ, COURSE_LEVEL_DESC, COURSE_NUMBER, COURSE_IDENTIFICATION, COURSE_LEVEL, COURSE_CLASSIFICATION_GROUPING, CAMPUS, CAMPUS_DESC, COLLEGE, COLLEGE_DESC, BUILDING1, BUILDING_DESC1, ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, 
START_DATE, ACADEMIC_PERIOD_DESC, WEEKDAYS, WEEKDAY_B, MEETING_TIME,
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '\ [^-]\d+',1, 1)),'HH24MI') AS TIME_START,
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '[^-]\d+[^,]', 1, 2)),'HH24MI') AS TIME_END,
TRIM(REGEXP_SUBSTR(MEETING_TIME, '[^,]+', 1, 1)) AS MEETING_TIME1,
SUBSTR(WEEKDAYS, 1,1) AS WEEKDAY
FROM DATA

UNION
SELECT UC_ENROLLMENT, UG_ENROLLMENT, UP_ENROLLMENT, US_ENROLLMENT, CP_ENROLLMENT, MIN_BILLING, MIN_CREDITS, MIN_LAB_HOURS, TOTAL_CREDIT_HOURS, TOTAL_ENROLLMENT, MAX_BILLING, MAX_CREDITS, MAX_LAB_HOURS, MAXIMUM_ENROLLMENT, ACTUAL_ENROLLMENT, GP_ENROLLMENT, GR_ENROLLMENT, END_DATE, SCHEDULE, INSTRUCTOR_JOB_GRADE, INSTRUCTOR_HR_DIV, INSTRUCTOR_HR_DIV_DESC,INSTRUCTOR_HR_DEPT_DESC, INSTRUCTOR_HR_DEPTID, HONORS_TYPE, FACULTY_TENURE, FACULTY_MEMBER_CATEGORY, ACADEMIC_RANK, TITLE_LONG_DESC, TITLE_SHORT_DESC, SUBJECT, SUBJECT_DESC, SCHEDULE_DESC, SECTION_CROSS_LIST,SCHEDULE_ATTRIBUTE_DESC1,SCHEDULE_ATTRIBUTE1,ROOM1, PRIMARY_INSTRUCTOR_LAST_NAME, PRIMARY_INSTRUCTOR_FIRST_NAME, INSTRUCTOR_ROLE, INSTRUCTIONAL_METHOD, INSTRUCTIONAL_METHOD_DESC, DEPARTMENT, DEPARTMENT_DESC, COURSE_NUMBER_COREQ, COURSE_LEVEL_DESC, COURSE_NUMBER, COURSE_IDENTIFICATION, COURSE_LEVEL, COURSE_CLASSIFICATION_GROUPING, CAMPUS, CAMPUS_DESC, COLLEGE, COLLEGE_DESC, BUILDING1, BUILDING_DESC1, ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, 
START_DATE, ACADEMIC_PERIOD_DESC, WEEKDAYS, WEEKDAY_B, MEETING_TIME, 
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '\ [^ ]\d+[^-]', 1, 2)),'HH24MI') AS TIME_START2,
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '[^-]\d+[^,]', 2, 4)),'HH24MI') AS TIME_END2,
TRIM(SUBSTR(MEETING_TIME, 13, Instr(MEETING_TIME, ',', -5, 1))) AS MEETING_TIME2,
SUBSTR(WEEKDAY_B, 1,1) AS WEEKDAY6
FROM DATA

UNION
SELECT UC_ENROLLMENT, UG_ENROLLMENT, UP_ENROLLMENT, US_ENROLLMENT, CP_ENROLLMENT, MIN_BILLING, MIN_CREDITS, MIN_LAB_HOURS, TOTAL_CREDIT_HOURS, TOTAL_ENROLLMENT, MAX_BILLING, MAX_CREDITS, MAX_LAB_HOURS, MAXIMUM_ENROLLMENT, ACTUAL_ENROLLMENT, GP_ENROLLMENT, GR_ENROLLMENT, END_DATE, SCHEDULE, INSTRUCTOR_JOB_GRADE, INSTRUCTOR_HR_DIV, INSTRUCTOR_HR_DIV_DESC,INSTRUCTOR_HR_DEPT_DESC, INSTRUCTOR_HR_DEPTID, HONORS_TYPE, FACULTY_TENURE, FACULTY_MEMBER_CATEGORY, ACADEMIC_RANK, TITLE_LONG_DESC, TITLE_SHORT_DESC, SUBJECT, SUBJECT_DESC, SCHEDULE_DESC, SECTION_CROSS_LIST,SCHEDULE_ATTRIBUTE_DESC1,SCHEDULE_ATTRIBUTE1,ROOM1, PRIMARY_INSTRUCTOR_LAST_NAME, PRIMARY_INSTRUCTOR_FIRST_NAME, INSTRUCTOR_ROLE, INSTRUCTIONAL_METHOD, INSTRUCTIONAL_METHOD_DESC, DEPARTMENT, DEPARTMENT_DESC, COURSE_NUMBER_COREQ, COURSE_LEVEL_DESC, COURSE_NUMBER, COURSE_IDENTIFICATION, COURSE_LEVEL, COURSE_CLASSIFICATION_GROUPING, CAMPUS, CAMPUS_DESC, COLLEGE, COLLEGE_DESC, BUILDING1, BUILDING_DESC1, ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, 
START_DATE, ACADEMIC_PERIOD_DESC, WEEKDAYS, WEEKDAY_B, MEETING_TIME, 
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '\ [^-]\d+',1, 1)),'HH24MI') AS TIME_START3,
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '[^-]\d+[^,]', 1, 2)),'HH24MI') AS TIME_END3,
TRIM(REGEXP_SUBSTR(MEETING_TIME, '[^,]+', 1, 1)) AS MEETING_TIME3,
SUBSTR(WEEKDAYS, 5,1) AS WEEKDAY3
FROM DATA

UNION
SELECT UC_ENROLLMENT, UG_ENROLLMENT, UP_ENROLLMENT, US_ENROLLMENT, CP_ENROLLMENT, MIN_BILLING, MIN_CREDITS, MIN_LAB_HOURS, TOTAL_CREDIT_HOURS, TOTAL_ENROLLMENT, MAX_BILLING, MAX_CREDITS, MAX_LAB_HOURS, MAXIMUM_ENROLLMENT, ACTUAL_ENROLLMENT, GP_ENROLLMENT, GR_ENROLLMENT, END_DATE, SCHEDULE, INSTRUCTOR_JOB_GRADE, INSTRUCTOR_HR_DIV, INSTRUCTOR_HR_DIV_DESC,INSTRUCTOR_HR_DEPT_DESC, INSTRUCTOR_HR_DEPTID, HONORS_TYPE, FACULTY_TENURE, FACULTY_MEMBER_CATEGORY, ACADEMIC_RANK, TITLE_LONG_DESC, TITLE_SHORT_DESC, SUBJECT, SUBJECT_DESC, SCHEDULE_DESC, SECTION_CROSS_LIST,SCHEDULE_ATTRIBUTE_DESC1,SCHEDULE_ATTRIBUTE1,ROOM1, PRIMARY_INSTRUCTOR_LAST_NAME, PRIMARY_INSTRUCTOR_FIRST_NAME, INSTRUCTOR_ROLE, INSTRUCTIONAL_METHOD, INSTRUCTIONAL_METHOD_DESC, DEPARTMENT, DEPARTMENT_DESC, COURSE_NUMBER_COREQ, COURSE_LEVEL_DESC, COURSE_NUMBER, COURSE_IDENTIFICATION, COURSE_LEVEL, COURSE_CLASSIFICATION_GROUPING, CAMPUS, CAMPUS_DESC, COLLEGE, COLLEGE_DESC, BUILDING1, BUILDING_DESC1, ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, 
START_DATE, ACADEMIC_PERIOD_DESC, WEEKDAYS, WEEKDAY_B, MEETING_TIME, 
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '\ [^-]\d+',1, 1)),'HH24MI') AS TIME_START4,
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '[^-]\d+[^,]', 1, 2)),'HH24MI') AS TIME_END4,
TRIM(REGEXP_SUBSTR(MEETING_TIME, '[^,]+', 1, 1)) AS MEETING_TIME4,
SUBSTR(WEEKDAYS, 7,1) AS WEEKDAY4
FROM DATA

UNION
SELECT UC_ENROLLMENT, UG_ENROLLMENT, UP_ENROLLMENT, US_ENROLLMENT, CP_ENROLLMENT, MIN_BILLING, MIN_CREDITS, MIN_LAB_HOURS, TOTAL_CREDIT_HOURS, TOTAL_ENROLLMENT, MAX_BILLING, MAX_CREDITS, MAX_LAB_HOURS, MAXIMUM_ENROLLMENT, ACTUAL_ENROLLMENT, GP_ENROLLMENT, GR_ENROLLMENT, END_DATE, SCHEDULE, INSTRUCTOR_JOB_GRADE, INSTRUCTOR_HR_DIV, INSTRUCTOR_HR_DIV_DESC,INSTRUCTOR_HR_DEPT_DESC, INSTRUCTOR_HR_DEPTID, HONORS_TYPE, FACULTY_TENURE, FACULTY_MEMBER_CATEGORY, ACADEMIC_RANK, TITLE_LONG_DESC, TITLE_SHORT_DESC, SUBJECT, SUBJECT_DESC, SCHEDULE_DESC, SECTION_CROSS_LIST,SCHEDULE_ATTRIBUTE_DESC1,SCHEDULE_ATTRIBUTE1,ROOM1, PRIMARY_INSTRUCTOR_LAST_NAME, PRIMARY_INSTRUCTOR_FIRST_NAME, INSTRUCTOR_ROLE, INSTRUCTIONAL_METHOD, INSTRUCTIONAL_METHOD_DESC, DEPARTMENT, DEPARTMENT_DESC, COURSE_NUMBER_COREQ, COURSE_LEVEL_DESC, COURSE_NUMBER, COURSE_IDENTIFICATION, COURSE_LEVEL, COURSE_CLASSIFICATION_GROUPING, CAMPUS, CAMPUS_DESC, COLLEGE, COLLEGE_DESC, BUILDING1, BUILDING_DESC1, ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, 
START_DATE, ACADEMIC_PERIOD_DESC, WEEKDAYS, WEEKDAY_B, MEETING_TIME, 
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '\ [^-]\d+',1, 1)),'HH24MI') AS TIME_START5,
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '[^-]\d+[^,]', 1, 2)),'HH24MI') AS TIME_END5,
TRIM(REGEXP_SUBSTR(MEETING_TIME, '[^,]+', 1, 1)) AS MEETING_TIME5,
SUBSTR(WEEKDAYS, 9,1) AS WEEKDAY5
FROM DATA

UNION
SELECT UC_ENROLLMENT, UG_ENROLLMENT, UP_ENROLLMENT, US_ENROLLMENT, CP_ENROLLMENT, MIN_BILLING, MIN_CREDITS, MIN_LAB_HOURS, TOTAL_CREDIT_HOURS, TOTAL_ENROLLMENT, MAX_BILLING, MAX_CREDITS, MAX_LAB_HOURS, MAXIMUM_ENROLLMENT, ACTUAL_ENROLLMENT, GP_ENROLLMENT, GR_ENROLLMENT, END_DATE, SCHEDULE, INSTRUCTOR_JOB_GRADE, INSTRUCTOR_HR_DIV, INSTRUCTOR_HR_DIV_DESC,INSTRUCTOR_HR_DEPT_DESC, INSTRUCTOR_HR_DEPTID, HONORS_TYPE, FACULTY_TENURE, FACULTY_MEMBER_CATEGORY, ACADEMIC_RANK, TITLE_LONG_DESC, TITLE_SHORT_DESC, SUBJECT, SUBJECT_DESC, SCHEDULE_DESC, SECTION_CROSS_LIST,SCHEDULE_ATTRIBUTE_DESC1,SCHEDULE_ATTRIBUTE1,ROOM1, PRIMARY_INSTRUCTOR_LAST_NAME, PRIMARY_INSTRUCTOR_FIRST_NAME, INSTRUCTOR_ROLE, INSTRUCTIONAL_METHOD, INSTRUCTIONAL_METHOD_DESC, DEPARTMENT, DEPARTMENT_DESC, COURSE_NUMBER_COREQ, COURSE_LEVEL_DESC, COURSE_NUMBER, COURSE_IDENTIFICATION, COURSE_LEVEL, COURSE_CLASSIFICATION_GROUPING, CAMPUS, CAMPUS_DESC, COLLEGE, COLLEGE_DESC, BUILDING1, BUILDING_DESC1, ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, 
START_DATE, ACADEMIC_PERIOD_DESC, WEEKDAYS, WEEKDAY_B, MEETING_TIME,
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '\ [^-]\d+',1, 1)),'HH24MI') AS TIME_START6,
to_date(TRIM(REGEXP_SUBSTR(MEETING_TIME, '[^-]\d+[^,]', 1, 2)),'HH24MI') AS TIME_END6,
TRIM(REGEXP_SUBSTR(MEETING_TIME, '[^,]+', 1, 1)) AS MEETING_TIME6,
SUBSTR(WEEKDAYS, 3,1) AS WEEKDAY2
FROM DATA
